# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e84f44607268e64a4256447a4005c9121762ead582b22bc09b5ec50a24c3b0e5186fd24cadda75fd76493170748a13244e499150d6684a56a59e266136380ed

test:
  secret_key_base: e2b29d857630fd113d9c9f3e63b93299b83440957ad297b9d18af082ba7ce7f7a89a60655312ee50fcbc4b125da7ec1e45c23261beb39d7e6de38b9d72f6f3ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
